name: Build and release app binaries
on: 
  push:
    branches:
      - main
jobs:
  release-binaries:
    name: Release app binaries to Github Releases
    runs-on: ubuntu-latest
    needs: build-artifacts
    steps:
      - name: Download app binaries
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Log
        run: ls
      - name: Create Github Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{github.run_number}}
          release_name: Release V${{github.run_number}}
      - name: Upload binaries to Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{github.run_number}}
          files: dist/ticky_0.1.0_amd64.deb

  build-artifacts:
    name: Build app binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: yarn install
      - name: Build binaries
        run: yarn electron:package:linux
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/